//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiTry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Table
    {
        public int book_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string book_choise { get; set; }
        public string book_name { get; set; }
        public string writer_name { get; set; }
    
        public virtual User_Table User_Table { get; set; }
    }
}
