//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiTry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary_Table
    {
        public int dictionary_id { get; set; }
        public string dictionary_tr { get; set; }
        public string dictionary_en { get; set; }
        public string dictionary_fr { get; set; }
        public string dictionary_de { get; set; }
        public string dictionary_es { get; set; }
    }
}
