//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiTry.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MadalyonContext : DbContext
    {
        public MadalyonContext()
            : base("name=MadalyonContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Currency_Table> Currency_Table { get; set; }
        public virtual DbSet<Dictionary_Table> Dictionary_Table { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Translate_Table> Translate_Table { get; set; }
        public virtual DbSet<User_Table> User_Table { get; set; }
        public virtual DbSet<User_Info_Table> User_Info_Table { get; set; }
        public virtual DbSet<Top_Book> Top_Book { get; set; }
        public virtual DbSet<Experience_Table> Experience_Table { get; set; }
        public virtual DbSet<Review_Table> Review_Table { get; set; }
        public virtual DbSet<Book_Table> Book_Table { get; set; }
        public virtual DbSet<Travel_Questions_Table> Travel_Questions_Table { get; set; }
        public virtual DbSet<Read_Questions_Table> Read_Questions_Table { get; set; }
        public virtual DbSet<Travel_Map_Table> Travel_Map_Table { get; set; }
    }
}
