//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiTry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review_Table
    {
        public int review_id { get; set; }
        public int user_id { get; set; }
        public string review_name { get; set; }
        public string review_text { get; set; }
        public string review_photo { get; set; }
    
        public virtual User_Table User_Table { get; set; }
    }
}
