//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiTry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel_Map_Table
    {
        public int Travel_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string travel_choise { get; set; }
        public string travel_city { get; set; }
        public string travel_country { get; set; }
        public Nullable<System.DateTime> travel_date { get; set; }
    
        public virtual User_Table User_Table { get; set; }
    }
}
