//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiTry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Info_Table
    {
        public int user_info_id { get; set; }
        public int user_id { get; set; }
        public Nullable<int> user_info_contact_no { get; set; }
        public string user_info_contact_email { get; set; }
        public string user_info_hobby { get; set; }
        public string user_info_travel { get; set; }
        public Nullable<System.DateTime> user_info_date { get; set; }
        public string user_info_book { get; set; }
        public Nullable<int> user_info_reliability { get; set; }
        public string user_info_city { get; set; }
    
        public virtual User_Table User_Table { get; set; }
    }
}
